# Generated by Django 4.2.11 on 2024-03-28 12:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organization', models.IntegerField(default=2000)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('favorite', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=True)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('notes', models.CharField(max_length=300)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=100)),
                ('source_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organization', models.IntegerField(default=2000)),
                ('group_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=100)),
                ('budget', models.BigIntegerField()),
                ('property_status', models.CharField(max_length=200)),
                ('booking_in_date', models.DateTimeField(auto_now_add=True)),
                ('purchase_reason', models.CharField(max_length=100)),
                ('loan_required', models.BooleanField(default=False)),
                ('notes', models.CharField(max_length=300)),
                ('bhk', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('1 BHK', '1 BHK'), ('1.5 BHK', '1.5 BHK'), ('2 BHK', '2 BHK'), ('2.5 BHK', '2.5 BHK'), ('3 BHK', '3 BHK'), ('4 BHK', '4 BHK'), ('5 BHK', '5 BHK')], max_length=20), blank=True, default=list, null=True, size=None)),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_requirement', to='app.lead')),
            ],
        ),
        migrations.CreateModel(
            name='LeadFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=300)),
                ('date_time', models.DateTimeField()),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_followup', to='app.lead')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.source'),
        ),
        migrations.AddField(
            model_name='lead',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.tag'),
        ),
    ]
