# Generated by Django 4.2.11 on 2024-03-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_requirement_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=200)),
                ('price_range_max', models.BigIntegerField()),
                ('price_range_min', models.BigIntegerField()),
            ],
        ),
    ]
