# Generated by Django 4.2.11 on 2024-03-29 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('booking_amount', models.BigIntegerField()),
                ('note', models.CharField(max_length=300)),
                ('cancelled', models.BooleanField(default=False)),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_id', to='app.lead')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_id', to='app.project')),
            ],
        ),
    ]
