# Generated by Django 4.2.11 on 2024-03-29 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='lead_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_id', to='app.lead'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_id', to='app.project'),
        ),
    ]
