# Generated by Django 4.2.11 on 2024-03-29 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_booking_lead_id_alter_booking_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='lead_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lead'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.project'),
        ),
    ]
