# Generated by Django 4.2.11 on 2024-03-30 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_closure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closure',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='app.project'),
        ),
    ]
