# Generated by Django 4.2.11 on 2024-03-30 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_closure_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closure',
            name='lead_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lead'),
        ),
        migrations.AlterField(
            model_name='closure',
            name='project_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='app.project'),
        ),
    ]
