# Generated by Django 4.2.11 on 2024-03-30 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_projectmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmatch',
            name='lead_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lead'),
        ),
        migrations.AlterField(
            model_name='projectmatch',
            name='project_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_id', to='app.project'),
        ),
    ]
