# Generated by Django 4.2.11 on 2024-04-06 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_projectmatch_lead_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmatch',
            name='lead_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lead'),
        ),
        migrations.AlterField(
            model_name='projectmatch',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_id', to='app.project'),
        ),
    ]
